name: Daily Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '0 6 * * *'   # 06:00 UTC
    - cron: '0 12 * * *'  # 12:00 UTC
    - cron: '0 18 * * *'  # 18:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make a dummy change
        run: |
          echo "Last updated: $(date -u)" > daily.txt

      - name: Commit and push
        run: |
          git config user.name "Raviteja Koyya"
          git config user.email "ravitejakoyya@users.noreply.github.com"
          git add daily.txt
          git commit -m "Daily update: $(date -u)" || echo "No changes to commit"
          git push
